stages:
  - build

build-elec:
  stage: build
  image:
    name: kicad/kicad:nightly
    pull_policy: if-not-present
  script:
    - mkdir -p build/gerbers
    - kicad-cli pcb export gerbers -o build/gerbers/ elec/layout/bike_light.kicad_pcb
  artifacts:
    paths:
      - build/
