stages:
  - check
  - build

build-elec:
  stage: build
  image:
    name: kicad/kicad:nightly
    pull_policy: if-not-present
  script:
    - mkdir -p build/src
    - cp elec/layouts/default/*.kicad_pcb build/src/
    - sed -i "s/"'{{GITHASH}}'"/$CI_COMMIT_SHORT_SHA/g" build/src/*.kicad_pcb
    - mkdir -p build/gerbers
    - kicad-cli pcb export gerbers -o build/gerbers/ build/src/*.kicad_pcb
    - kicad-cli pcb export drill -o build/gerbers/ build/src/*.kicad_pcb
    - zip "build/gerbers/gerbers-$CI_COMMIT_SHORT_SHA.zip" build/gerbers/*
  artifacts:
    paths:
      - build/

# TODO: figure out how to install atopile in this environment
# check-debug:
#   stage: check
#   image:
#     name: python:3.10
#     pull_policy: if-not-present
#   script:
#     - git clone https://gitlab.atopile.io/atopile/atopile.git
#     - pip install ./atopile
#     - ato check elec/src
